# Generated by Django 4.2.13 on 2024-05-08 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0003_remove_book_avaliblenumber_book_avalible"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="userBorrowedBy",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="BorrowBook",
        ),
    ]
