# Generated by Django 4.2.13 on 2024-05-08 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_book_userborrowedby_delete_borrowbook"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="userBorrowedBy",
            new_name="userBorrow",
        ),
    ]
