# Generated by Django 4.2.13 on 2024-05-08 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_userborrowedby_book_userborrow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="avalible",
            new_name="avaliable",
        ),
    ]
