# Generated by Django 4.2.10 on 2024-02-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resetcode",
            name="sendTime",
            field=models.DateTimeField(),
        ),
    ]
