# Generated by Django 4.2.13 on 2024-05-07 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Authentication", "0002_alter_resetcode_sendtime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="ResetCode",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
